#!/bin/sh
#
# Set up environment variables for general build tool to operate
#

export ZOPEN_TYPE="TARBALL"

export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make m4 perl autoconf tar gawk coreutils"

export ZOPEN_GIT_URL="https://github.com/autotools-mirror/automake.git"
export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake help2man makeinfo xz tar gawk"

export ZOPEN_EXTRA_CFLAGS=""
export ZOPEN_EXTRA_LDFLAGS=""
export PERL="/bin/env perl"

if [ "${ZOPEN_TYPE}x" = "TARBALLx" ]; then
	export ZOPEN_BOOTSTRAP=skip
fi

zopen_check_results()
{
chk="$1/$2_check.log"

failures=$(egrep '^ERROR|^FAIL' ${chk} | wc -l)
totalTests=$(egrep '^ERROR|^FAIL|^PASS' ${chk} | wc -l)

cat <<ZZ
actualFailures:$failures
totalTests:$totalTests
expectedFailures:2
ZZ
}
