#!/bin/sh
#
# Set up environment variables for general build tool to operate
#

export ZOPEN_BUILD_LINE="STABLE"

# bump: automake-version /AUTOMAKE_VERSION="(.*)"/ https://ftp.gnu.org/gnu/automake/|re:/href="automake-([\d.]+).tar.gz"/$1/|semver:*
AUTOMAKE_VERSION="1.16.5"
export ZOPEN_STABLE_URL="https://ftp.gnu.org/gnu/automake/automake-${AUTOMAKE_VERSION}.tar.gz"
export ZOPEN_STABLE_DEPS="curl gzip make m4 perl autoconf tar gawk coreutils help2man"

export ZOPEN_DEV_URL="https://github.com/autotools-mirror/automake.git"
export ZOPEN_DEV_DEPS="git make m4 perl autoconf automake help2man texinfo xz tar gawk"

export ZOPEN_EXTRA_CFLAGS=""
export ZOPEN_EXTRA_LDFLAGS=""
export PERL="/bin/env perl"

if [ "${ZOPEN_BUILD_LINE}x" = "STABLEx" ]; then
	export ZOPEN_BOOTSTRAP=skip
fi

zopen_check_results()
{
chk="$1/$2_check.log"

failures=$(egrep '^ERROR|^FAIL' ${chk} | wc -l)
totalTests=$(egrep '^ERROR|^FAIL|^PASS' ${chk} | wc -l)

cat <<ZZ
actualFailures:$failures
totalTests:$totalTests
expectedFailures:2
ZZ
}

zopen_get_version(){
 ./configure --version | head -1 | awk '{ print $4 }'
}
